- hosts: localhost
  gather_facts: yes
  roles:
    - prometheus.prometheus.node_exporter
  pre_tasks:
    - name: check firewalld service status
      service_facts:
    - name: stop firewalld
      systemd:
        name: firewalld
        state: stopped
      when: ansible_facts.services['firewalld.service']['status'] == 'enabled'
  post_tasks:
    - name: start firewalld
      systemd:
        name: firewalld
        state: started
      when: ansible_facts.services['firewalld.service']['status'] == 'enabled'

    - name: permit node_exporter
      ansible.posix.firewalld:
        port: 9100/tcp
        permanent: true
        immediate: yes
        state: enabled
      when: ansible_facts.services['firewalld.service']['status'] == 'enabled'
  tasks:
    - name: url
      uri:
        url: "http://localhost:9100/metrics"
        method: "GET"
    - name: register to consul
      uri:
        method: "PUT"
        url: "{{ consul_url }}"
        body_format: json
        body:
          Node: "{{ ansible_hostname}}"
          Address: "{{ ansible_default_ipv4.address }}"
          NodeMeta:
            external-node: "true"
            external-probe": "true"
          Service:
            ID: "node_exporter"
            Service: "node_exporter"
            Tags: ["node_exporter", "prometheus"]
            Port: 9100
          Checks:
            - Name: "http-check"
              status: "passing"
              Definition:
                http: "http://{{ ansible_default_ipv4.address }}:9100"
                interval: "30s"
