- hosts: localhost
  gather_facts: yes
  roles:
    - prometheus.prometheus.node_exporter
  pre_tasks:
    - name: stop firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
  post_tasks:
  tasks:
    - name: url
      uri:
        url: "http://localhost:9100/metrics"
        method: "GET"
    - name: register to consul
      uri:
        method: "PUT"
        url: "{{ consul_url }}"
        body_format: json
        body:
          Node: "{{ ansible_hostname}}"
          Address: "{{ ansible_default_ipv4.address }}"
          NodeMeta:
            external-node: "true"
            external-probe": "true"
          Service:
            ID: "node_exporter"
            Service: "node_exporter"
            Tags: ["node_exporter", "prometheus"]
            Port: 9100
          Checks:
            - Name: "http-check"
              status: "passing"
              Definition:
                http: "http://{{ ansible_default_ipv4.address }}:9100"
                interval: "30s"
